# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import copy
import gc
import hashlib
import hmac
import json
import math
import os
import random
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import nibabel as nib
import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import StratifiedGroupKFold
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, Dataset
from torchvision.models.video import Swin3D_S_Weights, swin3d_s


# ==============================================================================
# 0. CONFIG
# ==============================================================================

CONFIG = {
    # image
    "depth": 32,
    "size": 224,

    # token grid used for cross-attention
    # torchvision Swin3D-S final feature map for 32x224x224 is typically
    # 16 x 7 x 7. We pool the temporal axis to 4 while preserving 7x7 spatial
    # resolution -> N = 4*7*7 = 196 tokens, which is non-degenerate and much
    # more memory-efficient than N = 784.
    "token_pool_t": 4,
    "token_pool_h": 7,
    "token_pool_w": 7,

    # model
    "num_heads": 8,
    "attn_dropout": 0.10,
    "ffn_dropout": 0.10,

    # training
    "batch_size": 2,           # token attention uses more VRAM
    "accum_steps": 8,          # effective batch ~16
    "num_workers": 8,
    "epochs": 80,
    "patience": 12,
    "lr": 1e-4,
    "weight_decay": 0.05,
    "mixup_alpha": 0.2,
    "n_fold": 5,
    "seed": 42,

    # optional SWA; default off for cleaner early-stopping behavior
    "use_swa": False,
    "swa_start": 60,

    # paths
    "paths": {
        "3d+": "data/post",
        "3d-": "data/pre",
        "diff": "data/diff",
    },
    "plaque_csv": "data/plaque_labels.csv",
    "subject_csv": "data/subjects.csv",

    # Plaque-level classifier ensemble (used for Stage-1 evaluation only).
    "classifier_model_dir": "outputs/stage1/classifier_checkpoints",
    "eval_dir": "outputs/stage1/evaluation",

    # Leakage-free downstream encoders for the patient-level model.
    # The fold manifest is generated by the Stage-2 script from Training patients only.
    "fold_manifest": "outputs/folds/outer_folds.csv",
    "strict_model_dir": "outputs/stage1/strict_encoders",
    "strict_feature_dir": "outputs/stage1/strict_features",
    "inner_n_splits": 5,
}

TASKS = ["vuln", "iph", "lrnc", "irr", "enh"]
TASK_LABEL_COLUMNS = {
    "vuln": "label",
    "iph": "IPH",
    "lrnc": "LRNC",
    "irr": "Irregular",
    "enh": "Enhancement",
}


# ==============================================================================
# 1. Reproducibility / helpers
# ==============================================================================

def seed_everything(seed: int) -> None:
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def canonical_group(x: str) -> str:
    s = str(x).strip().lower().replace("_", " ").replace("-", " ")
    if s in {"train", "training"}:
        return "train"
    if s in {"val", "valid", "validation"}:
        return "validation"
    if s in {"test", "external test", "externaltest", "external"}:
        return "test"
    if s in {"prospective", "prospective validation", "temporal", "temporal validation"}:
        return "prospective"
    return s


def clean_plaque_name(x: object) -> str:
    name = str(x).strip()
    for suffix in (".nii.gz", ".nii.npy", ".npy"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    return name


def binary_label(v: object) -> int:
    if pd.isna(v):
        raise ValueError("A binary label is missing.")
    value = float(v)
    if not np.isfinite(value) or value not in (0.0, 1.0):
        raise ValueError("Binary labels must be encoded as 0 or 1.")
    return int(value)


def protected_subject_key(subject_id: object) -> str:
    secret = os.environ.get("PIPELINE_LINK_KEY")
    if not secret:
        raise RuntimeError(
            "Set PIPELINE_LINK_KEY in the local environment before feature extraction."
        )
    raw = str(subject_id).strip().encode("utf-8")
    return hmac.new(secret.encode("utf-8"), raw, hashlib.sha256).hexdigest()


seed_everything(CONFIG["seed"])

if torch.cuda.is_available():
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True


# ==============================================================================
# 2. EfficientKAN
# ==============================================================================

class EfficientKANLinear(nn.Module):
    def __init__(
        self,
        in_features: int,
        out_features: int,
        grid_size: int = 5,
        spline_order: int = 3,
        scale_noise: float = 0.1,
        scale_base: float = 1.0,
        scale_spline: float = 1.0,
        enable_standalone_scale_spline: bool = True,
        base_activation=nn.SiLU,
        grid_eps: float = 0.02,
        grid_range: Tuple[float, float] = (-1.0, 1.0),
    ):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.grid_size = grid_size
        self.spline_order = spline_order
        self.scale_base = scale_base
        self.scale_spline = scale_spline
        self.enable_standalone_scale_spline = enable_standalone_scale_spline
        self.grid_eps = grid_eps
        self.base_activation = base_activation()

        h = (grid_range[1] - grid_range[0]) / grid_size
        grid = (
            torch.arange(-spline_order, grid_size + spline_order + 1) * h
            + grid_range[0]
        ).expand(in_features, -1).contiguous()
        self.register_buffer("grid", grid)

        self.base_weight = nn.Parameter(torch.empty(out_features, in_features))
        self.spline_weight = nn.Parameter(
            torch.empty(out_features, in_features, grid_size + spline_order)
        )
        if enable_standalone_scale_spline:
            self.spline_scaler = nn.Parameter(torch.empty(out_features, in_features))
        else:
            self.register_parameter("spline_scaler", None)

        self.reset_parameters(scale_noise)

    def reset_parameters(self, scale_noise: float = 0.1) -> None:
        nn.init.kaiming_uniform_(self.base_weight, a=math.sqrt(5) * self.scale_base)
        with torch.no_grad():
            noise = (
                torch.rand(
                    self.grid_size + 1,
                    self.in_features,
                    self.out_features,
                    device=self.base_weight.device,
                )
                - 0.5
            ) * scale_noise / self.grid_size

            coeff = self.curve2coeff(
                self.grid.T[self.spline_order : -self.spline_order], noise
            )
            scale = (
                self.scale_spline
                if not self.enable_standalone_scale_spline
                else 1.0
            )
            self.spline_weight.copy_(scale * coeff)

            if self.spline_scaler is not None:
                nn.init.kaiming_uniform_(
                    self.spline_scaler, a=math.sqrt(5) * self.scale_spline
                )

    def b_splines(self, x: torch.Tensor) -> torch.Tensor:
        grid = self.grid
        x = x.unsqueeze(-1)
        bases = ((x >= grid[:, :-1]) & (x < grid[:, 1:])).to(x.dtype)

        for k in range(1, self.spline_order + 1):
            left_num = x - grid[:, : -(k + 1)]
            left_den = grid[:, k:-1] - grid[:, : -(k + 1)]
            right_num = grid[:, k + 1 :] - x
            right_den = grid[:, k + 1 :] - grid[:, 1:-k]
            bases = (
                left_num / (left_den + 1e-12) * bases[:, :, :-1]
                + right_num / (right_den + 1e-12) * bases[:, :, 1:]
            )

        return bases.contiguous()

    def curve2coeff(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        A = self.b_splines(x).transpose(0, 1)
        B = y.transpose(0, 1)
        solution = torch.linalg.lstsq(A, B).solution
        return solution.permute(2, 0, 1).contiguous()

    @property
    def scaled_spline_weight(self) -> torch.Tensor:
        return self.spline_weight * (
            self.spline_scaler.unsqueeze(-1)
            if self.enable_standalone_scale_spline
            else 1.0
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        original_shape = x.shape
        x2 = x.reshape(-1, self.in_features)

        base_output = F.linear(self.base_activation(x2), self.base_weight)
        spline_output = F.linear(
            self.b_splines(x2).reshape(x2.shape[0], -1),
            self.scaled_spline_weight.reshape(self.out_features, -1),
        )

        y = base_output + spline_output
        return y.reshape(*original_shape[:-1], self.out_features)


# ==============================================================================
# 3. Token-level architecture
# ==============================================================================

class SharedSwin3DTokenEncoder(nn.Module):
    """
    ONE Swin3D-S encoder is reused for both pre- and post-contrast volumes.

    It returns a real token sequence rather than a single pooled vector:
        [B, 3, D, H, W]
          -> Swin feature map [B, T', H', W', 768]
          -> adaptive token pooling
          -> [B, N, 768], N = pool_t * pool_h * pool_w
    """

    def __init__(self, pool_size: Tuple[int, int, int]):
        super().__init__()
        backbone = swin3d_s(weights=Swin3D_S_Weights.KINETICS400_V1)

        self.patch_embed = backbone.patch_embed
        self.pos_drop = backbone.pos_drop
        self.features = backbone.features
        self.norm = backbone.norm
        self.feat_dim = int(backbone.head.in_features)
        self.pool_size = tuple(int(v) for v in pool_size)

        # Remove the temporary top-level object; modules above retain weights.
        del backbone

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B,3,D,H,W]
        x = self.patch_embed(x)      # [B,T,H,W,C]
        x = self.pos_drop(x)
        x = self.features(x)
        x = self.norm(x)             # [B,T',H',W',C]

        # -> [B,C,T',H',W']
        x = x.permute(0, 4, 1, 2, 3).contiguous()
        x = F.adaptive_avg_pool3d(x, self.pool_size)

        # -> [B,N,C]
        x = x.flatten(2).transpose(1, 2).contiguous()
        return x


class CrossAttentionBlock(nn.Module):
    """
    Standard pre-norm multi-head cross-attention with a residual FFN.

    query_tokens and context_tokens can both have N > 1.
    """

    def __init__(
        self,
        dim: int,
        num_heads: int = 8,
        attn_dropout: float = 0.1,
        ffn_dropout: float = 0.1,
        mlp_ratio: float = 2.0,
    ):
        super().__init__()
        self.norm_q = nn.LayerNorm(dim)
        self.norm_kv = nn.LayerNorm(dim)
        self.attn = nn.MultiheadAttention(
            embed_dim=dim,
            num_heads=num_heads,
            dropout=attn_dropout,
            batch_first=True,
        )
        self.attn_drop = nn.Dropout(attn_dropout)

        hidden = int(dim * mlp_ratio)
        self.norm_ffn = nn.LayerNorm(dim)
        self.ffn = nn.Sequential(
            nn.Linear(dim, hidden),
            nn.GELU(),
            nn.Dropout(ffn_dropout),
            nn.Linear(hidden, dim),
            nn.Dropout(ffn_dropout),
        )

    def forward(
        self,
        query_tokens: torch.Tensor,
        context_tokens: torch.Tensor,
        return_attention: bool = False,
    ):
        q = self.norm_q(query_tokens)
        kv = self.norm_kv(context_tokens)

        attn_out, attn_map = self.attn(
            q,
            kv,
            kv,
            need_weights=return_attention,
            average_attn_weights=False if return_attention else True,
        )
        x = query_tokens + self.attn_drop(attn_out)
        x = x + self.ffn(self.norm_ffn(x))

        if return_attention:
            return x, attn_map
        return x


class SubtractionGuidedGate(nn.Module):
    """
    Uses the global subtraction feature to modulate a cross-attended
    pre/post representation without pretending that the subtraction branch
    itself contains a matching 3D token grid.
    """

    def __init__(self, dim: int):
        super().__init__()
        self.diff_proj = nn.Sequential(
            nn.Linear(dim, dim),
            nn.LayerNorm(dim),
            nn.GELU(),
        )
        self.gate = nn.Sequential(
            nn.Linear(dim * 2, dim),
            nn.Sigmoid(),
        )
        self.out_norm = nn.LayerNorm(dim)

    def forward(
        self, main_feature: torch.Tensor, diff_feature: torch.Tensor
    ) -> torch.Tensor:
        d = self.diff_proj(diff_feature)
        g = self.gate(torch.cat([main_feature, d], dim=1))
        return self.out_norm(main_feature + g * d)


class PlaquePhenNet(nn.Module):
    """
    Plaque-level multi-task architecture.

    pre/post:
        shared Swin3D-S -> token sequences -> bidirectional cross-attention

    subtraction:
        ConvNeXt V2-Tiny (32 depth slices treated as channels) -> 768-D guide

    fusion:
        cross-attended pre/post global features + subtraction-guided gates
        -> concat -> LayerNorm -> 1536-D plaque representation

    phenotype heads:
        1536 -> 256 -> 2  (x4)

    Vuln relay:
        1536 + 2*4 = 1544 -> 512 -> 2
    """

    def __init__(self):
        super().__init__()

        pool_size = (
            CONFIG["token_pool_t"],
            CONFIG["token_pool_h"],
            CONFIG["token_pool_w"],
        )

        # ONE shared-weight Swin encoder
        self.shared_swin = SharedSwin3DTokenEncoder(pool_size=pool_size)
        self.feat_dim = self.shared_swin.feat_dim  # 768

        # subtraction encoder: ConvNeXt V2-Tiny
        self.diff_encoder = timm.create_model(
            "convnextv2_tiny",
            pretrained=True,
            num_classes=0,
            in_chans=CONFIG["depth"],
        )
        self.diff_align = nn.Linear(self.diff_encoder.num_features, self.feat_dim)
        self.diff_norm = nn.LayerNorm(self.feat_dim)

        # REAL token-level bidirectional cross-attention
        self.pre_queries_post = CrossAttentionBlock(
            self.feat_dim,
            num_heads=CONFIG["num_heads"],
            attn_dropout=CONFIG["attn_dropout"],
            ffn_dropout=CONFIG["ffn_dropout"],
        )
        self.post_queries_pre = CrossAttentionBlock(
            self.feat_dim,
            num_heads=CONFIG["num_heads"],
            attn_dropout=CONFIG["attn_dropout"],
            ffn_dropout=CONFIG["ffn_dropout"],
        )

        # subtraction-guided modulation
        self.pre_diff_gate = SubtractionGuidedGate(self.feat_dim)
        self.post_diff_gate = SubtractionGuidedGate(self.feat_dim)

        # 768 + 768 = 1536
        self.fusion_norm = nn.LayerNorm(self.feat_dim * 2)

        def build_aux_head(num_classes: int = 2) -> nn.Sequential:
            return nn.Sequential(
                EfficientKANLinear(self.feat_dim * 2, 256),
                nn.LayerNorm(256),
                nn.SiLU(),
                nn.Dropout(0.50),
                EfficientKANLinear(256, num_classes),
            )

        self.head_iph = build_aux_head(2)
        self.head_lrnc = build_aux_head(2)
        self.head_irr = build_aux_head(2)
        self.head_enh = build_aux_head(2)

        # Four phenotype heads each output two logits -> +8
        self.relay_dim = self.feat_dim * 2 + 8
        self.head_vuln = nn.Sequential(
            EfficientKANLinear(self.relay_dim, 512),
            nn.LayerNorm(512),
            nn.SiLU(),
            nn.Dropout(0.65),
            EfficientKANLinear(512, 2),
        )

    def encode_plaque(
        self,
        x_pre: torch.Tensor,
        x_post: torch.Tensor,
        x_diff: torch.Tensor,
        return_attention: bool = False,
    ):
        # pre/post are one-channel volumes; Kinetics-pretrained Swin expects 3 ch
        x_pre_3ch = x_pre.repeat(1, 3, 1, 1, 1)
        x_post_3ch = x_post.repeat(1, 3, 1, 1, 1)

        # IMPORTANT: both calls use the SAME self.shared_swin -> shared weights
        pre_tokens = self.shared_swin(x_pre_3ch)
        post_tokens = self.shared_swin(x_post_3ch)

        if pre_tokens.shape[1] <= 1 or post_tokens.shape[1] <= 1:
            raise RuntimeError(
                f"Cross-attention token count must be >1, got "
                f"pre={pre_tokens.shape}, post={post_tokens.shape}"
            )

        if return_attention:
            pre_cross, attn_pre = self.pre_queries_post(
                pre_tokens, post_tokens, return_attention=True
            )
            post_cross, attn_post = self.post_queries_pre(
                post_tokens, pre_tokens, return_attention=True
            )
        else:
            pre_cross = self.pre_queries_post(pre_tokens, post_tokens)
            post_cross = self.post_queries_pre(post_tokens, pre_tokens)
            attn_pre = attn_post = None

        # token -> global
        pre_global = pre_cross.mean(dim=1)
        post_global = post_cross.mean(dim=1)

        # subtraction: [B,1,32,H,W] -> [B,32,H,W]
        diff_2d = x_diff.squeeze(1)
        diff_global = self.diff_encoder(diff_2d)
        diff_global = self.diff_norm(self.diff_align(diff_global))

        # explicit subtraction-guided gating
        pre_guided = self.pre_diff_gate(pre_global, diff_global)
        post_guided = self.post_diff_gate(post_global, diff_global)

        plaque_feature = self.fusion_norm(
            torch.cat([pre_guided, post_guided], dim=1)
        )  # [B,1536]

        if return_attention:
            return plaque_feature, {
                "pre_queries_post": attn_pre,
                "post_queries_pre": attn_post,
                "token_count": int(pre_tokens.shape[1]),
            }

        return plaque_feature

    def forward_features(
        self, x_pre: torch.Tensor, x_post: torch.Tensor, x_diff: torch.Tensor
    ) -> torch.Tensor:
        return self.encode_plaque(x_pre, x_post, x_diff, return_attention=False)

    def forward(
        self,
        x_pre: torch.Tensor,
        x_post: torch.Tensor,
        x_diff: torch.Tensor,
        return_attention: bool = False,
    ):
        if return_attention:
            feat, attn_info = self.encode_plaque(
                x_pre, x_post, x_diff, return_attention=True
            )
        else:
            feat = self.encode_plaque(
                x_pre, x_post, x_diff, return_attention=False
            )
            attn_info = None

        out_iph = self.head_iph(feat)
        out_lrnc = self.head_lrnc(feat)
        out_irr = self.head_irr(feat)
        out_enh = self.head_enh(feat)

        relay_feat = torch.cat(
            [feat, out_iph, out_lrnc, out_irr, out_enh], dim=1
        )  # [B,1544]
        out_vuln = self.head_vuln(relay_feat)

        output = {
            "vuln": out_vuln,
            "iph": out_iph,
            "lrnc": out_lrnc,
            "irr": out_irr,
            "enh": out_enh,
            "plaque_feature": feat,
        }
        if return_attention:
            output["attention"] = attn_info
        return output


# ==============================================================================
# 4. Loss
# ==============================================================================

class ASLSingleLabel(nn.Module):
    def __init__(
        self,
        gamma_neg: float = 4.0,
        gamma_pos: float = 1.0,
        eps: float = 0.0,
        reduction: str = "mean",
    ):
        super().__init__()
        self.gamma_neg = gamma_neg
        self.gamma_pos = gamma_pos
        self.eps = eps
        self.reduction = reduction
        self.logsoftmax = nn.LogSoftmax(dim=-1)

    def forward(self, inputs: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        if inputs.ndim != 2:
            raise ValueError("ASLSingleLabel expects logits with shape [B, C].")
        if target.ndim != 1:
            target = target.reshape(-1)
        if inputs.shape[0] != target.shape[0]:
            raise ValueError("Logits and targets must have the same batch size.")

        num_classes = inputs.size(-1)
        log_preds = self.logsoftmax(inputs)

        targets = torch.zeros_like(inputs).scatter_(
            1, target.long().unsqueeze(1), 1.0
        )
        anti_targets = 1.0 - targets

        probs = torch.exp(log_preds)
        xs_pos = probs * targets
        xs_neg = (1.0 - probs) * anti_targets

        asymmetric_w = torch.pow(
            1.0 - xs_pos - xs_neg,
            self.gamma_pos * targets + self.gamma_neg * anti_targets,
        )
        log_preds = log_preds * asymmetric_w

        if self.eps > 0:
            targets = targets.mul(1.0 - self.eps).add(self.eps / num_classes)

        loss = -(targets * log_preds).sum(dim=-1)

        if self.reduction == "mean":
            return loss.mean()
        if self.reduction == "sum":
            return loss.sum()
        if self.reduction == "none":
            return loss
        raise ValueError("reduction must be 'mean', 'sum', or 'none'.")


class MultiTaskLossWrapper(nn.Module):
    def __init__(self, num_tasks: int = 5):
        super().__init__()
        self.log_vars = nn.Parameter(torch.zeros(num_tasks))

    def forward(self, losses: List[torch.Tensor]) -> torch.Tensor:
        if len(losses) != len(self.log_vars):
            raise ValueError("Loss count does not match learned task weights.")
        total = 0.0
        for i, loss in enumerate(losses):
            precision = torch.exp(-self.log_vars[i])
            total = total + precision * loss + 0.5 * self.log_vars[i]
        return total


def mixup_criterion(
    criterion: nn.Module,
    pred: torch.Tensor,
    y_a: torch.Tensor,
    y_b: torch.Tensor,
    lam: float,
) -> torch.Tensor:
    return lam * criterion(pred, y_a) + (1.0 - lam) * criterion(pred, y_b)


# ==============================================================================
# 5. Dataset
# ==============================================================================

class PlaqueDataset(Dataset):
    def __init__(self, df: pd.DataFrame, is_train: bool = False):
        self.df = df.reset_index(drop=True).copy()
        self.is_train = is_train

    def __len__(self) -> int:
        return len(self.df)

    def _load_volume(self, folder: str, name: str) -> torch.Tensor:
        path = Path(folder) / f"{name}.nii.gz"
        if not path.is_file():
            raise FileNotFoundError("Required input file was not found.")

        arr = nib.load(str(path)).get_fdata().astype(np.float32)
        t = torch.from_numpy(arr).unsqueeze(0)  # [1,D,H,W]

        t = F.interpolate(
            t.unsqueeze(0),
            size=(CONFIG["depth"], CONFIG["size"], CONFIG["size"]),
            mode="trilinear",
            align_corners=False,
        ).squeeze(0)

        return t

    def __getitem__(self, i: int):
        row = self.df.iloc[i]
        name = clean_plaque_name(row["ID"])

        v_pre = self._load_volume(CONFIG["paths"]["3d-"], name)
        v_post = self._load_volume(CONFIG["paths"]["3d+"], name)
        v_diff = self._load_volume(CONFIG["paths"]["diff"], name)

        # Normalize paired inputs; subtraction input is assumed precomputed
        v_pre = (v_pre - v_pre.mean()) / (v_pre.std() + 1e-6)
        v_post = (v_post - v_post.mean()) / (v_post.std() + 1e-6)

        labels = torch.tensor(
            [
                binary_label(row.get("label", 0)),
                binary_label(row.get("IPH", 0)),
                binary_label(row.get("LRNC", 0)),
                binary_label(row.get("Irregular", 0)),
                binary_label(row.get("Enhancement", 0)),
            ],
            dtype=torch.long,
        )

        if self.is_train:
            # Apply exactly the same geometric transform to all three inputs.
            if random.random() < 0.5:
                v_pre = torch.flip(v_pre, [-1])
                v_post = torch.flip(v_post, [-1])
                v_diff = torch.flip(v_diff, [-1])

            if random.random() < 0.5:
                v_pre = torch.flip(v_pre, [-2])
                v_post = torch.flip(v_post, [-2])
                v_diff = torch.flip(v_diff, [-2])

            k = random.randint(0, 3)
            if k > 0:
                v_pre = torch.rot90(v_pre, k, [-2, -1])
                v_post = torch.rot90(v_post, k, [-2, -1])
                v_diff = torch.rot90(v_diff, k, [-2, -1])

        return v_pre, v_post, v_diff, labels, name


# ==============================================================================
# 6. Training-only threshold locking
# ==============================================================================

def locked_threshold_path() -> Path:
    return Path(CONFIG["classifier_model_dir"]) / "locked_thresholds.json"


def select_youden_threshold(y_true: np.ndarray, y_prob: np.ndarray) -> float:
    """Select a binary decision threshold using Youden's J on Training OOF data."""
    y_true = np.asarray(y_true, dtype=int)
    y_prob = np.asarray(y_prob, dtype=float)

    if len(np.unique(y_true)) != 2:
        raise ValueError("Threshold selection requires both binary classes.")
    if not np.all(np.isfinite(y_prob)):
        raise ValueError("Threshold selection received non-finite probabilities.")

    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    finite = np.isfinite(thresholds)
    if not np.any(finite):
        raise RuntimeError("No finite ROC threshold was available.")

    j = tpr - fpr
    best_j = np.max(j[finite])
    candidate_idx = np.where(finite & np.isclose(j, best_j, rtol=0.0, atol=1e-12))[0]

    # Deterministic tie-break: choose the candidate closest to 0.5.
    idx = candidate_idx[np.argmin(np.abs(thresholds[candidate_idx] - 0.5))]
    return float(np.clip(thresholds[idx], 0.0, 1.0))


def save_locked_thresholds(oof_predictions: pd.DataFrame) -> Dict[str, float]:
    thresholds: Dict[str, float] = {}
    for task in TASKS:
        thresholds[task] = select_youden_threshold(
            oof_predictions[f"true_{task}"].to_numpy(),
            oof_predictions[f"prob_{task}"].to_numpy(),
        )

    path = locked_threshold_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "selection_method": "youden_j",
        "selection_source": "training_oof",
        "thresholds": thresholds,
    }
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    return thresholds


def load_locked_thresholds() -> Dict[str, float]:
    path = locked_threshold_path()
    if not path.is_file():
        raise FileNotFoundError(
            "Locked thresholds were not found. Run --mode lock-thresholds first."
        )
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    thresholds = payload.get("thresholds", {})
    if set(thresholds) != set(TASKS):
        raise ValueError("Locked threshold file does not contain all tasks.")

    clean: Dict[str, float] = {}
    for task in TASKS:
        value = float(thresholds[task])
        if not np.isfinite(value) or value < 0.0 or value > 1.0:
            raise ValueError("Locked thresholds must be finite values in [0, 1].")
        clean[task] = value
    return clean


# ==============================================================================
# 7. Training
# ==============================================================================

def make_loader(
    df: pd.DataFrame, is_train: bool, batch_size: Optional[int] = None
) -> DataLoader:
    ds = PlaqueDataset(df, is_train=is_train)
    return DataLoader(
        ds,
        batch_size=batch_size or CONFIG["batch_size"],
        shuffle=is_train,
        num_workers=CONFIG["num_workers"],
        pin_memory=torch.cuda.is_available(),
        persistent_workers=CONFIG["num_workers"] > 0,
    )


@torch.no_grad()
def predict_vuln_auc(
    model: nn.Module, loader: DataLoader, device: torch.device
) -> float:
    model.eval()
    y_true: List[int] = []
    y_prob: List[float] = []

    for pre, post, diff, labels, _ in loader:
        pre = pre.to(device, non_blocking=True)
        post = post.to(device, non_blocking=True)
        diff = diff.to(device, non_blocking=True)

        amp_enabled = device.type == "cuda"
        with autocast("cuda", dtype=torch.bfloat16, enabled=amp_enabled):
            out = model(pre, post, diff)

        p = torch.softmax(out["vuln"].float(), dim=1)[:, 1]
        y_prob.extend(p.cpu().numpy().tolist())
        y_true.extend(labels[:, 0].numpy().tolist())

    if len(np.unique(y_true)) < 2:
        return float("nan")
    return float(roc_auc_score(y_true, y_prob))


def run_classifier_training() -> None:
    device = get_device()
    model_dir = Path(CONFIG["classifier_model_dir"])
    model_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(CONFIG["plaque_csv"])
    if "group" not in df.columns:
        raise ValueError("Plaque CSV must contain a 'group' column.")

    for col in ["IPH", "LRNC", "Irregular", "Enhancement"]:
        if col not in df.columns:
            raise ValueError(f"Plaque CSV missing phenotype column: {col}")

    groups = df["group"].map(canonical_group)
    train_df = df[groups == "train"].reset_index(drop=True)

    if len(train_df) == 0:
        raise ValueError("No training samples were found.")


    subject_df = pd.read_csv(CONFIG["subject_csv"], dtype={"ID": str})
    if "ID" not in subject_df.columns:
        raise ValueError("Subject CSV must contain an 'ID' column.")

    subject_df["ID"] = subject_df["ID"].astype(str).str.strip()
    plaque_to_subject = build_plaque_patient_map(train_df, subject_df)
    patient_groups = np.asarray(
        [plaque_to_subject[clean_plaque_name(x)] for x in train_df["ID"]],
        dtype=object,
    )

    if len(np.unique(patient_groups)) < CONFIG["n_fold"]:
        raise ValueError("The number of unique subjects is smaller than n_fold.")

    skf = StratifiedGroupKFold(
        n_splits=CONFIG["n_fold"],
        shuffle=True,
        random_state=CONFIG["seed"],
    )

    y_strat = train_df["label"].astype(int).to_numpy()

    for fold, (tr_idx, in_val_idx) in enumerate(
        skf.split(train_df, y_strat, groups=patient_groups)
    ):
        train_subjects = set(patient_groups[tr_idx])
        val_subjects = set(patient_groups[in_val_idx])
        if train_subjects.intersection(val_subjects):
            raise RuntimeError("Subject overlap detected between fold partitions.")

        tr_df = train_df.iloc[tr_idx].reset_index(drop=True)
        in_val_df = train_df.iloc[in_val_idx].reset_index(drop=True)

        tr_dl = make_loader(tr_df, is_train=True)
        in_val_dl = make_loader(in_val_df, is_train=False)

        model = PlaquePhenNet().to(device)
        loss_wrapper = MultiTaskLossWrapper(num_tasks=5).to(device)
        loss_fn = ASLSingleLabel(gamma_neg=4, gamma_pos=1, eps=0.0)

        optimizer = torch.optim.AdamW(
            [
                {"params": model.parameters(), "lr": CONFIG["lr"]},
                {"params": loss_wrapper.parameters(), "lr": 1e-3},
            ],
            weight_decay=CONFIG["weight_decay"],
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=CONFIG["epochs"]
        )

        scaler = GradScaler("cuda", enabled=device.type == "cuda")

        best_auc = -np.inf
        best_epoch = -1
        best_state = None
        best_loss_state = None
        patience_count = 0

        # Optional SWA state
        swa_state = None
        swa_n = 0

        for epoch in range(CONFIG["epochs"]):
            model.train()
            optimizer.zero_grad(set_to_none=True)

            epoch_losses: List[float] = []
            for step, (pre, post, diff, labels, _) in enumerate(tr_dl):
                pre = pre.to(device, non_blocking=True)
                post = post.to(device, non_blocking=True)
                diff = diff.to(device, non_blocking=True)
                labels = labels.to(device, non_blocking=True)

                amp_enabled = device.type == "cuda"
                with autocast(
                    "cuda", dtype=torch.bfloat16, enabled=amp_enabled
                ):
                    if CONFIG["mixup_alpha"] > 0:
                        lam = float(
                            np.random.beta(
                                CONFIG["mixup_alpha"], CONFIG["mixup_alpha"]
                            )
                        )
                        perm = torch.randperm(pre.size(0), device=device)

                        out = model(
                            lam * pre + (1.0 - lam) * pre[perm],
                            lam * post + (1.0 - lam) * post[perm],
                            lam * diff + (1.0 - lam) * diff[perm],
                        )

                        losses = []
                        for task_idx, task in enumerate(TASKS):
                            y = labels[:, task_idx]
                            losses.append(
                                mixup_criterion(
                                    loss_fn,
                                    out[task],
                                    y,
                                    y[perm],
                                    lam,
                                )
                            )
                    else:
                        out = model(pre, post, diff)
                        losses = []
                        for task_idx, task in enumerate(TASKS):
                            y = labels[:, task_idx]
                            losses.append(
                                loss_fn(out[task], y)
                            )

                    total_loss = loss_wrapper(losses)
                    scaled_loss = total_loss / CONFIG["accum_steps"]

                scaler.scale(scaled_loss).backward()

                should_step = (
                    (step + 1) % CONFIG["accum_steps"] == 0
                    or (step + 1) == len(tr_dl)
                )
                if should_step:
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)

                epoch_losses.append(float(total_loss.detach().cpu()))

            scheduler.step()

            # optional simple parameter averaging after swa_start
            if CONFIG["use_swa"] and epoch >= CONFIG["swa_start"]:
                current = copy.deepcopy(model.state_dict())
                if swa_state is None:
                    swa_state = {
                        k: v.detach().clone() for k, v in current.items()
                    }
                    swa_n = 1
                else:
                    swa_n += 1
                    alpha = 1.0 / swa_n
                    for k in swa_state:
                        swa_state[k].mul_(1.0 - alpha).add_(
                            current[k], alpha=alpha
                        )

            auc = predict_vuln_auc(model, in_val_dl, device)
            mean_loss = float(np.mean(epoch_losses))

            improved = np.isfinite(auc) and auc > best_auc + 1e-6
            if improved:
                best_auc = auc
                best_epoch = epoch
                best_state = copy.deepcopy(model.state_dict())
                best_loss_state = copy.deepcopy(loss_wrapper.state_dict())
                patience_count = 0
            else:
                patience_count += 1


            if patience_count >= CONFIG["patience"]:
                break

        if best_state is None:
            raise RuntimeError(f"Fold {fold}: no valid best state was found.")

        # If SWA was enabled, compare it against best checkpoint on internal fold val
        if CONFIG["use_swa"] and swa_state is not None:
            swa_model = PlaquePhenNet().to(device)
            swa_model.load_state_dict(swa_state, strict=True)
            swa_auc = predict_vuln_auc(swa_model, in_val_dl, device)
            if np.isfinite(swa_auc) and swa_auc > best_auc:
                best_auc = swa_auc
                best_state = copy.deepcopy(swa_state)
                best_epoch = -2
            del swa_model

        checkpoint = {"model_state_dict": best_state}

        ckpt_path = model_dir / f"best_fold{fold}.pth"
        torch.save(checkpoint, ckpt_path)

        del model, optimizer, scaler, tr_dl, in_val_dl
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Derive task-specific thresholds exclusively from patient-grouped
    # Training OOF predictions and save them with the Stage-1 checkpoints.
    run_threshold_locking()


# ==============================================================================
# 8. Checkpoint loading / evaluation
# ==============================================================================

def load_classifier_models(device: torch.device) -> List[PlaquePhenNet]:
    models: List[PlaquePhenNet] = []
    for fold in range(CONFIG["n_fold"]):
        path = Path(CONFIG["classifier_model_dir"]) / f"best_fold{fold}.pth"
        if not path.is_file():
            raise FileNotFoundError("A required model checkpoint was not found.")

        ckpt = torch.load(path, map_location="cpu")
        state = (
            ckpt["model_state_dict"]
            if isinstance(ckpt, dict) and "model_state_dict" in ckpt
            else ckpt
        )

        model = PlaquePhenNet()
        model.load_state_dict(state, strict=True)
        model.to(device).eval()
        models.append(model)

    return models


@torch.no_grad()
def run_threshold_locking() -> None:
    """Lock task-specific cutoffs from patient-grouped Training OOF predictions."""
    device = get_device()

    df = pd.read_csv(CONFIG["plaque_csv"])
    if "group" not in df.columns:
        raise ValueError("Plaque CSV must contain a 'group' column.")

    groups = df["group"].map(canonical_group)
    train_df = df[groups == "train"].reset_index(drop=True)
    if len(train_df) == 0:
        raise ValueError("No training samples were found.")

    subject_df = pd.read_csv(CONFIG["subject_csv"], dtype={"ID": str})
    if "ID" not in subject_df.columns:
        raise ValueError("Subject CSV must contain an 'ID' column.")
    subject_df["ID"] = subject_df["ID"].astype(str).str.strip()

    plaque_to_subject = build_plaque_patient_map(train_df, subject_df)
    patient_groups = np.asarray(
        [plaque_to_subject[clean_plaque_name(x)] for x in train_df["ID"]],
        dtype=object,
    )

    splitter = StratifiedGroupKFold(
        n_splits=CONFIG["n_fold"],
        shuffle=True,
        random_state=CONFIG["seed"],
    )
    y_strat = train_df["label"].astype(int).to_numpy()
    models = load_classifier_models(device)

    oof_frames: List[pd.DataFrame] = []
    seen = np.zeros(len(train_df), dtype=np.int8)

    for fold, (_, hold_idx) in enumerate(
        splitter.split(train_df, y_strat, groups=patient_groups)
    ):
        seen[hold_idx] += 1
        hold_df = train_df.iloc[hold_idx].reset_index(drop=True)
        hold_loader = make_loader(
            hold_df, is_train=False, batch_size=CONFIG["batch_size"]
        )
        oof_frames.append(predict_ensemble([models[fold]], hold_loader, device))

    if not np.all(seen == 1):
        raise RuntimeError("Training OOF partitioning did not cover each sample exactly once.")

    oof_predictions = pd.concat(oof_frames, ignore_index=True)
    if len(oof_predictions) != len(train_df):
        raise RuntimeError("Training OOF prediction count does not match the training set.")

    save_locked_thresholds(oof_predictions)


@torch.no_grad()
def predict_ensemble(
    models: List[PlaquePhenNet],
    loader: DataLoader,
    device: torch.device,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for pre, post, diff, labels, names in loader:
        pre = pre.to(device, non_blocking=True)
        post = post.to(device, non_blocking=True)
        diff = diff.to(device, non_blocking=True)

        probs_by_task = {
            task: np.zeros((len(names),), dtype=np.float64)
            for task in TASKS
        }

        for model in models:
            amp_enabled = device.type == "cuda"
            with autocast(
                "cuda", dtype=torch.bfloat16, enabled=amp_enabled
            ):
                out = model(pre, post, diff)

            for task in TASKS:
                p = (
                    torch.softmax(out[task].float(), dim=1)[:, 1]
                    .detach()
                    .cpu()
                    .numpy()
                )
                probs_by_task[task] += p / len(models)

        labels_np = labels.numpy()

        for i, _ in enumerate(names):
            row: Dict[str, object] = {}
            for task_idx, task in enumerate(TASKS):
                row[f"true_{task}"] = int(labels_np[i, task_idx])
                row[f"prob_{task}"] = float(probs_by_task[task][i])
            rows.append(row)

    return pd.DataFrame(rows)


def classification_metrics(
    y_true: np.ndarray, y_prob: np.ndarray, threshold: float
) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=int)
    y_prob = np.asarray(y_prob, dtype=float)
    threshold = float(threshold)
    if not np.isfinite(threshold) or threshold < 0.0 or threshold > 1.0:
        raise ValueError("Threshold must be a finite value in [0, 1].")
    y_pred = (y_prob >= threshold).astype(int)

    out: Dict[str, float] = {"Threshold": threshold}
    if len(np.unique(y_true)) >= 2:
        out["AUC"] = float(roc_auc_score(y_true, y_prob))
        out["AP"] = float(average_precision_score(y_true, y_prob))
    else:
        out["AUC"] = float("nan")
        out["AP"] = float("nan")

    out["Accuracy"] = float(accuracy_score(y_true, y_pred))
    out["F1"] = float(f1_score(y_true, y_pred, zero_division=0))

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    out["Sensitivity"] = float(tp / (tp + fn)) if tp + fn else float("nan")
    out["Specificity"] = float(tn / (tn + fp)) if tn + fp else float("nan")
    out["PPV"] = float(tp / (tp + fp)) if tp + fp else float("nan")
    out["NPV"] = float(tn / (tn + fn)) if tn + fn else float("nan")
    out["Brier"] = float(np.mean((y_prob - y_true) ** 2))
    return out


def run_evaluation() -> None:
    device = get_device()
    eval_dir = Path(CONFIG["eval_dir"])
    eval_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(CONFIG["plaque_csv"])
    groups = df["group"].map(canonical_group)
    models = load_classifier_models(device)
    locked_thresholds = load_locked_thresholds()

    all_metric_rows = []

    for split_name, split_key in [
        ("Validation", "validation"),
        ("Test", "test"),
        ("Prospective", "prospective"),
    ]:
        subset = df[groups == split_key].reset_index(drop=True)
        if len(subset) == 0:
            continue

        loader = make_loader(
            subset, is_train=False, batch_size=CONFIG["batch_size"]
        )
        pred_df = predict_ensemble(models, loader, device)
        pred_path = eval_dir / f"{split_name}_predictions.csv"
        export_cols = [c for c in pred_df.columns if c.startswith("prob_")]
        export_df = pred_df[export_cols].copy()
        export_df.insert(0, "sample_index", np.arange(len(export_df), dtype=int))
        export_df.to_csv(pred_path, index=False, encoding="utf-8-sig")

        for task in TASKS:
            m = classification_metrics(
                pred_df[f"true_{task}"].to_numpy(),
                pred_df[f"prob_{task}"].to_numpy(),
                threshold=locked_thresholds[task],
            )
            m["Cohort"] = split_name
            m["Task"] = task
            all_metric_rows.append(m)


    metrics_df = pd.DataFrame(all_metric_rows)
    metrics_path = eval_dir / "stage1_metrics.csv"
    metrics_df.to_csv(metrics_path, index=False, encoding="utf-8-sig")


# ==============================================================================
# 9. Feature extraction
# ==============================================================================

def load_single_case(
    plaque_name: str, device: torch.device
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    def load(key: str) -> torch.Tensor:
        path = Path(CONFIG["paths"][key]) / f"{plaque_name}.nii.gz"
        if not path.is_file():
            raise FileNotFoundError("Required input file was not found.")

        arr = nib.load(str(path)).get_fdata().astype(np.float32)
        t = torch.from_numpy(arr).unsqueeze(0)  # [1,D,H,W]
        t = F.interpolate(
            t.unsqueeze(0),
            size=(CONFIG["depth"], CONFIG["size"], CONFIG["size"]),
            mode="trilinear",
            align_corners=False,
        ).squeeze(0)

        if key != "diff":
            t = (t - t.mean()) / (t.std() + 1e-6)

        return t.unsqueeze(0).to(device)

    return load("3d-"), load("3d+"), load("diff")


def build_plaque_patient_map(
    plaque_df: pd.DataFrame, subject_df: pd.DataFrame
) -> Dict[str, str]:
    """
    Prefer an explicit patient-level ID column when available.
    Otherwise use a conservative longest-prefix fallback.

    If your plaque CSV has a dedicated patient ID column, rename it to PatientID
    for the cleanest mapping.
    """
    explicit_cols = [
        c for c in ["PatientID", "patient_id", "PID", "pid"]
        if c in plaque_df.columns
    ]

    mapping: Dict[str, str] = {}

    if explicit_cols:
        col = explicit_cols[0]
        valid_patient_ids = set(subject_df["ID"].astype(str).str.strip())
        for _, row in plaque_df.iterrows():
            plaque_name = clean_plaque_name(row["ID"])
            pid = str(row[col]).strip()
            if pid not in valid_patient_ids:
                raise ValueError("A subject linkage value could not be matched.")
            mapping[plaque_name] = pid
        return mapping

    patient_ids = subject_df["ID"].astype(str).str.strip().tolist()
    patient_ids_sorted = sorted(patient_ids, key=len, reverse=True)

    for plaque_raw in plaque_df["ID"]:
        plaque_name = clean_plaque_name(plaque_raw)

        # First try exact ID
        if plaque_name in patient_ids:
            mapping[plaque_name] = plaque_name
            continue

        candidates = []
        for pid in patient_ids_sorted:
            if not plaque_name.startswith(pid):
                continue
            if len(plaque_name) == len(pid):
                candidates.append(pid)
                continue

            next_char = plaque_name[len(pid)]
            # preferred boundary
            if next_char in {"_", "-", ".", " "}:
                candidates.append(pid)

        if not candidates:
            # last-resort: unique longest raw prefix
            raw_candidates = [
                pid for pid in patient_ids_sorted if plaque_name.startswith(pid)
            ]
            if raw_candidates:
                longest = len(raw_candidates[0])
                raw_candidates = [
                    p for p in raw_candidates if len(p) == longest
                ]
            if len(raw_candidates) == 1:
                candidates = raw_candidates

        if len(candidates) != 1:
            raise ValueError("A sample could not be uniquely linked to a subject.")

        mapping[plaque_name] = candidates[0]

    return mapping


@torch.no_grad()

# ==============================================================================
# 10. Leakage-free, fold-aligned Stage-1 encoders for Stage 2
# ==============================================================================

def _load_fold_manifest() -> pd.DataFrame:
    path = Path(CONFIG["fold_manifest"])
    if not path.is_file():
        raise FileNotFoundError(
            "The outer-fold manifest was not found. Generate it with the Stage-2 script first."
        )
    m = pd.read_csv(path, dtype={"link_key": str})
    required = {"link_key", "outer_fold"}
    missing = required.difference(m.columns)
    if missing:
        raise ValueError(f"Fold manifest missing columns: {sorted(missing)}")
    m["link_key"] = m["link_key"].astype(str).str.strip()
    m["outer_fold"] = m["outer_fold"].astype(int)
    if m["link_key"].duplicated().any():
        raise ValueError("Duplicate linkage keys were found in the fold manifest.")
    if set(m["outer_fold"]) != set(range(CONFIG["n_fold"])):
        raise ValueError("Fold manifest must contain every outer fold exactly within 0..n_fold-1.")
    return m


def _subject_linkage(subject_df: pd.DataFrame) -> Dict[str, str]:
    if "ID" not in subject_df.columns:
        raise ValueError("Subject CSV must contain an 'ID' column.")
    out = {}
    for raw in subject_df["ID"].astype(str).str.strip():
        key = protected_subject_key(raw)
        if key in out:
            raise ValueError("Duplicate protected linkage key detected.")
        out[key] = raw
    return out


def _strict_outer_partition(
    train_df: pd.DataFrame,
    subject_df: pd.DataFrame,
    outer_fold: int,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    manifest = _load_fold_manifest().set_index("link_key")
    plaque_to_subject = build_plaque_patient_map(train_df, subject_df)

    hold_mask = []
    for plaque_raw in train_df["ID"]:
        plaque_name = clean_plaque_name(plaque_raw)
        pid = plaque_to_subject[plaque_name]
        link_key = protected_subject_key(pid)
        if link_key not in manifest.index:
            raise ValueError("A Training subject is missing from the outer-fold manifest.")
        hold_mask.append(int(manifest.loc[link_key, "outer_fold"]) == outer_fold)

    hold_mask = np.asarray(hold_mask, dtype=bool)
    outer_hold = train_df.loc[hold_mask].reset_index(drop=True)
    outer_fit = train_df.loc[~hold_mask].reset_index(drop=True)
    if len(outer_hold) == 0 or len(outer_fit) == 0:
        raise ValueError("An outer fold produced an empty fit or holdout subset.")
    return outer_fit, outer_hold


def _make_inner_split(
    outer_fit_df: pd.DataFrame,
    subject_df: pd.DataFrame,
    seed: int,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    plaque_to_subject = build_plaque_patient_map(outer_fit_df, subject_df)
    patient_groups = np.asarray(
        [plaque_to_subject[clean_plaque_name(x)] for x in outer_fit_df["ID"]],
        dtype=object,
    )
    n_subjects = len(np.unique(patient_groups))
    n_splits = min(int(CONFIG["inner_n_splits"]), n_subjects)
    if n_splits < 2:
        raise ValueError("At least two subjects are required for inner checkpoint selection.")

    splitter = StratifiedGroupKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=seed,
    )
    y = outer_fit_df["label"].astype(int).to_numpy()

    for tr_idx, va_idx in splitter.split(outer_fit_df, y, groups=patient_groups):
        y_tr = y[tr_idx]
        y_va = y[va_idx]
        if len(np.unique(y_tr)) == 2 and len(np.unique(y_va)) == 2:
            return (
                outer_fit_df.iloc[tr_idx].reset_index(drop=True),
                outer_fit_df.iloc[va_idx].reset_index(drop=True),
            )
    raise RuntimeError("No valid inner split with both classes was available.")


def _new_optimizer(model: nn.Module, loss_wrapper: nn.Module):
    optimizer = torch.optim.AdamW(
        [
            {"params": model.parameters(), "lr": CONFIG["lr"]},
            {"params": loss_wrapper.parameters(), "lr": 1e-3},
        ],
        weight_decay=CONFIG["weight_decay"],
    )
    return optimizer


def _train_epoch(
    model: nn.Module,
    loss_wrapper: nn.Module,
    loader: DataLoader,
    optimizer,
    scaler: GradScaler,
    device: torch.device,
) -> float:
    model.train()
    optimizer.zero_grad(set_to_none=True)
    loss_fn = ASLSingleLabel(gamma_neg=4, gamma_pos=1, eps=0.0)
    values: List[float] = []

    for step, (pre, post, diff, labels, _) in enumerate(loader):
        pre = pre.to(device, non_blocking=True)
        post = post.to(device, non_blocking=True)
        diff = diff.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        amp_enabled = device.type == "cuda"
        with autocast("cuda", dtype=torch.bfloat16, enabled=amp_enabled):
            if CONFIG["mixup_alpha"] > 0:
                lam = float(np.random.beta(CONFIG["mixup_alpha"], CONFIG["mixup_alpha"]))
                perm = torch.randperm(pre.size(0), device=device)
                out = model(
                    lam * pre + (1.0 - lam) * pre[perm],
                    lam * post + (1.0 - lam) * post[perm],
                    lam * diff + (1.0 - lam) * diff[perm],
                )
                losses = []
                for task_idx, task in enumerate(TASKS):
                    y = labels[:, task_idx]
                    losses.append(mixup_criterion(loss_fn, out[task], y, y[perm], lam))
            else:
                out = model(pre, post, diff)
                losses = [loss_fn(out[t], labels[:, i]) for i, t in enumerate(TASKS)]

            total = loss_wrapper(losses)
            scaled = total / CONFIG["accum_steps"]

        scaler.scale(scaled).backward()
        should_step = ((step + 1) % CONFIG["accum_steps"] == 0) or ((step + 1) == len(loader))
        if should_step:
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
        values.append(float(total.detach().cpu()))

    return float(np.mean(values))


def _select_epoch_without_outer_holdout(
    inner_train_df: pd.DataFrame,
    inner_val_df: pd.DataFrame,
    seed: int,
) -> int:
    seed_everything(seed)
    device = get_device()
    train_loader = make_loader(inner_train_df, is_train=True)
    val_loader = make_loader(inner_val_df, is_train=False)

    model = PlaquePhenNet().to(device)
    loss_wrapper = MultiTaskLossWrapper(num_tasks=5).to(device)
    optimizer = _new_optimizer(model, loss_wrapper)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"])
    scaler = GradScaler("cuda", enabled=device.type == "cuda")

    best_auc = -np.inf
    best_epoch = None
    patience_count = 0

    for epoch in range(CONFIG["epochs"]):
        _train_epoch(model, loss_wrapper, train_loader, optimizer, scaler, device)
        scheduler.step()
        auc = predict_vuln_auc(model, val_loader, device)
        if np.isfinite(auc) and auc > best_auc + 1e-6:
            best_auc = auc
            best_epoch = epoch + 1
            patience_count = 0
        else:
            patience_count += 1
        if patience_count >= CONFIG["patience"]:
            break

    if best_epoch is None:
        raise RuntimeError("Inner checkpoint selection did not produce a valid epoch.")

    del model, loss_wrapper, optimizer, scheduler, scaler, train_loader, val_loader
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return int(best_epoch)


def _refit_outer_model(
    outer_fit_df: pd.DataFrame,
    n_epochs: int,
    seed: int,
) -> Dict[str, torch.Tensor]:
    """Refit on all outer-fit patients for the inner-selected epoch count."""
    seed_everything(seed)
    device = get_device()
    loader = make_loader(outer_fit_df, is_train=True)
    model = PlaquePhenNet().to(device)
    loss_wrapper = MultiTaskLossWrapper(num_tasks=5).to(device)
    optimizer = _new_optimizer(model, loss_wrapper)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(1, int(n_epochs))
    )
    scaler = GradScaler("cuda", enabled=device.type == "cuda")

    for _ in range(int(n_epochs)):
        _train_epoch(model, loss_wrapper, loader, optimizer, scaler, device)
        scheduler.step()

    state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
    del model, loss_wrapper, optimizer, scheduler, scaler, loader
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return state


def run_strict_encoder_training() -> None:
    """
    Train a fold-aligned Stage-1 encoder bank for downstream survival modeling.

    For outer fold k, the outer-holdout subjects are never used for Stage-1
    weight fitting, checkpoint/epoch selection, feature selection, or any other
    learned operation. Epoch selection is performed only inside the outer-fit
    subjects, after which a fresh model is refit on all outer-fit subjects.
    """
    model_dir = Path(CONFIG["strict_model_dir"])
    model_dir.mkdir(parents=True, exist_ok=True)

    plaque_df = pd.read_csv(CONFIG["plaque_csv"])
    groups = plaque_df["group"].map(canonical_group)
    train_df = plaque_df[groups == "train"].reset_index(drop=True)
    subject_df = pd.read_csv(CONFIG["subject_csv"], dtype={"ID": str})
    subject_df["ID"] = subject_df["ID"].astype(str).str.strip()

    # Validate manifest coverage before any model is fitted.
    manifest = _load_fold_manifest()
    subject_links = {protected_subject_key(x) for x in subject_df["ID"]}
    unknown = set(manifest["link_key"]) - subject_links
    if unknown:
        raise ValueError("Fold manifest contains linkage keys absent from the subject table.")

    for outer_fold in range(CONFIG["n_fold"]):
        outer_fit, outer_hold = _strict_outer_partition(train_df, subject_df, outer_fold)

        # Inner split is used only to select training duration; outer holdout is untouched.
        inner_train, inner_val = _make_inner_split(
            outer_fit, subject_df, seed=CONFIG["seed"] + 1000 + outer_fold
        )
        best_epoch_count = _select_epoch_without_outer_holdout(
            inner_train, inner_val, seed=CONFIG["seed"] + 2000 + outer_fold
        )
        final_state = _refit_outer_model(
            outer_fit,
            n_epochs=best_epoch_count,
            seed=CONFIG["seed"] + 3000 + outer_fold,
        )

        checkpoint = {
            "model_state_dict": final_state,
            "outer_fold": int(outer_fold),
            "selected_epoch_count": int(best_epoch_count),
            "note": "Outer-holdout subjects were excluded from all Stage-1 fitting and epoch selection.",
        }
        torch.save(checkpoint, model_dir / f"strict_outer_fold{outer_fold}.pth")


def load_strict_encoder(outer_fold: int, device: torch.device) -> PlaquePhenNet:
    path = Path(CONFIG["strict_model_dir"]) / f"strict_outer_fold{outer_fold}.pth"
    if not path.is_file():
        raise FileNotFoundError("A required strict Stage-1 encoder checkpoint was not found.")
    ckpt = torch.load(path, map_location="cpu")
    model = PlaquePhenNet()
    model.load_state_dict(ckpt["model_state_dict"], strict=True)
    return model.to(device).eval()


@torch.no_grad()
def run_strict_feature_extraction() -> None:
    """
    Export one patient-level plaque-feature dictionary per outer fold.

    No fold-specific features are averaged here. Stage 2 consumes fold-k features
    with fold-k survival modeling, and external predictions are ensembled only at
    the final risk-score level.
    """
    device = get_device()
    plaque_df = pd.read_csv(CONFIG["plaque_csv"])
    subject_df = pd.read_csv(CONFIG["subject_csv"], dtype={"ID": str})
    if "ID" not in subject_df.columns:
        raise ValueError("Subject CSV must contain an 'ID' column.")
    subject_df["ID"] = subject_df["ID"].astype(str).str.strip()
    plaque_map = build_plaque_patient_map(plaque_df, subject_df)

    out_dir = Path(CONFIG["strict_feature_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    for outer_fold in range(CONFIG["n_fold"]):
        model = load_strict_encoder(outer_fold, device)
        patient_data: Dict[str, Dict[str, object]] = {}

        for _, prow in plaque_df.iterrows():
            plaque_name = clean_plaque_name(prow["ID"])
            pid = plaque_map[plaque_name]
            subject_key = protected_subject_key(pid)
            pre, post, diff = load_single_case(plaque_name, device)

            amp_enabled = device.type == "cuda"
            with autocast("cuda", dtype=torch.bfloat16, enabled=amp_enabled):
                feat = model.forward_features(pre, post, diff).float().cpu().numpy()[0]

            loc_onehot = np.zeros(6, dtype=np.float32)
            loc = int(float(prow.get("LOCATION", -1)))
            if 0 <= loc <= 5:
                loc_onehot[loc] = 1.0
            spatial = np.concatenate(
                [
                    loc_onehot,
                    np.asarray([float(prow.get("RL", 0)), float(prow.get("QH", 0))], dtype=np.float32),
                ]
            ).astype(np.float32)

            item = patient_data.setdefault(subject_key, {"feats": [], "spatial": []})
            item["feats"].append(feat.astype(np.float32))
            item["spatial"].append(spatial)

        finalized: Dict[str, Dict[str, object]] = {}
        for subject_key, item in patient_data.items():
            feats = np.stack(item["feats"], axis=0).astype(np.float32)
            spatial = np.stack(item["spatial"], axis=0).astype(np.float32)
            if feats.shape[1] != 1536 or spatial.shape[1] != 8:
                raise AssertionError("Unexpected feature dimensionality.")
            finalized[subject_key] = {"feats": feats, "spatial": spatial}

        np.save(out_dir / f"strict_features_fold{outer_fold}.npy", finalized)
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


# ==============================================================================
# 11. CLI
# ==============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plaque-level multi-task modeling with leakage-free fold-aligned feature export."
    )
    parser.add_argument(
        "--mode",
        choices=[
            "train-classifier",
            "lock-thresholds",
            "evaluate",
            "train-strict-encoders",
            "extract-strict-features",
        ],
        required=True,
    )
    parser.add_argument("--plaque-csv", type=str, default=CONFIG["plaque_csv"])
    parser.add_argument("--subject-csv", type=str, default=CONFIG["subject_csv"])
    parser.add_argument("--pre-dir", type=str, default=CONFIG["paths"]["3d-"])
    parser.add_argument("--post-dir", type=str, default=CONFIG["paths"]["3d+"])
    parser.add_argument("--diff-dir", type=str, default=CONFIG["paths"]["diff"])
    parser.add_argument("--classifier-model-dir", type=str, default=CONFIG["classifier_model_dir"])
    parser.add_argument("--eval-dir", type=str, default=CONFIG["eval_dir"])
    parser.add_argument("--fold-manifest", type=str, default=CONFIG["fold_manifest"])
    parser.add_argument("--strict-model-dir", type=str, default=CONFIG["strict_model_dir"])
    parser.add_argument("--strict-feature-dir", type=str, default=CONFIG["strict_feature_dir"])
    return parser.parse_args()


def apply_args(args: argparse.Namespace) -> None:
    CONFIG["plaque_csv"] = args.plaque_csv
    CONFIG["subject_csv"] = args.subject_csv
    CONFIG["paths"]["3d-"] = args.pre_dir
    CONFIG["paths"]["3d+"] = args.post_dir
    CONFIG["paths"]["diff"] = args.diff_dir
    CONFIG["classifier_model_dir"] = args.classifier_model_dir
    CONFIG["eval_dir"] = args.eval_dir
    CONFIG["fold_manifest"] = args.fold_manifest
    CONFIG["strict_model_dir"] = args.strict_model_dir
    CONFIG["strict_feature_dir"] = args.strict_feature_dir


def main() -> None:
    args = parse_args()
    apply_args(args)
    if args.mode == "train-classifier":
        run_classifier_training()
    elif args.mode == "lock-thresholds":
        run_threshold_locking()
    elif args.mode == "evaluate":
        run_evaluation()
    elif args.mode == "train-strict-encoders":
        run_strict_encoder_training()
    elif args.mode == "extract-strict-features":
        run_strict_feature_extraction()
    else:
        raise ValueError(args.mode)


if __name__ == "__main__":
    main()
